version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./config/configuration.yaml:/app/config/configuration.yaml
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8081
  frontend:
    build:
      context: ./web
    ports:
      - "3000:80"
